### PR TITLE
EZP-26834: new language + flags

### PR DESCRIPTION
**Pull request by nicolas-bastien**
Jira : https://jira.ez.no/browse/EZP-26834

# Description

Add new package for languages added on crowdin 

Add flag store on an issue in github to enhance READMEs

### CODE REVIEW

**Comment by yannickroger** [comment]
That's a HUGE load of copy pasting. We are duplicating all the readmes and composer.json it might be a pain to keep up to date in the future.

Can't these file be generated based on a config file (that would be at the root of the language's folder) while extracting the language packages?

**Comment by bdunogier** [comment]
It would be a nice improvement, @yannickroger, but for the time being it is more important that we release the translations, I think.

**Comment by bdunogier** [comment]
One question though: the translations do not require kernel 6.7 but 6.8, where the TranslationPass was added, don't they ?

**Comment by bdunogier** [comment]
The kernel requirement question aside, +1.

**Review by bdunogier — APPROVED** [review]

**Review by yannickroger — APPROVED** [review]

**Comment by nicolas-bastien** [comment]
@bdunogier done fro 6.8

@yannickroger I thought about it and then I think it's better to have it separately cause : 

- it's simple to make a replace on the project if we have to change text
- this allow us to make custom description for each packages ex : a ask for help and translation or something else...

**Pull request merged**
